### ISSUE TITLE
ZeroDivision error with focus area of 100% width

### ISSUE THREAD

**Issue by lucasmoeskops** [fabrique/wagtail-easy-thumbnails#2]
I seem to be getting a float division by zero error when my focus-area has a 100% width.

**Comment by binairo** [comment]
Good point, will fix asap. Also another reason to write tests 😬

**Comment by lucasmoeskops** [comment]
Possible solution: https://github.com/fabrique/wagtail-easy-thumbnails/pull/3

**Comment by binairo** [comment]
This has been fixed in 0.3. Only happened in very specific cases where the ratio was triggering a division by zero error. Thanks, @lucasmoeskops for the solution.
